### ISSUE TITLE
Add a GitHub Action to automatically scan for vulnerable dependencies and output alerts.

### ISSUE THREAD

**Issue by thinkAfCod** [optimism-java/hildr#207]
or add a gradle plugin

**Comment by kengoon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/optimismj).

### My background and how it can be leveraged
I'm a software engineer with a strong skill on android (Java/Python). I have written github actions to fasciltate deploying android packages on maven repositories, I have  also written actions to build android apks/aab. checkout my github profile here https://github.com/kengoon

### How I plan on tackling this issue
I would start by creating a workflow that triggers on push and pull request, then in the workflow I will setup a jdk version to use depending on the version OptimismJ is already using. I will then build the project to install all dependencies. Next, I will integrate The OWASP Dependency-Check action to scan build.gradle file for any known vulnerabilities in the dependencies section. If any vulnerabilities are found, the report is uploaded as an artifact for review. Finally, I will create a step to checks if the previous step failed due to vulnerabilities, and outputs a message to the workflow logs

**Comment by kengoon** [comment]
@GrapeBaBa is the workflow disabled on forks? I can't run my actions

**Comment by kengoon** [comment]
also what severity level are we looking at?

0.0 - 3.9: Low severity
4.0 - 6.9: Medium severity
7.0 - 8.9: High severity
9.0 - 10.0: Critical severity

**Comment by kengoon** [comment]
@GrapeBaBa I wasn't rewarded for this project on onlydust
